[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "packerpy"
readme = "README.md"
requires_python = ">=3.8"
license = {text = "License :: OSI Approved :: GNU General Public License (GPL)"}
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License (GPL)"
]
