[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "packerpy"
readme = "README.md"
requires_python = ">=3.8"
license = {text = "BSD 2-Clause License"}
classifiers = [
    "Programming Language :: Python :: 3",
]
