[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "packerpy"
readme = "README.md"
requires_python = ">=3.8"

[metadata]
url = ""
license = "BSD 3-Clause License"
classifiers = [
    "License :: OSI Approved :: BSD License",
    "Programming Language :: Python :: 3",
]
